### ISSUE TITLE
Code source?

### ISSUE THREAD

**Issue by benitoelgringo** [oumaymatb/Local_Stochastic_Volatility#1]
Bonjour,

Je ne vois que le fichier Readme.md, mais il n'y a pas de code source.
Pourriez-vous le rajouter s'il vous plait?

**Comment by oumaymatb** [comment]
Bonjour Monsieur,

Oui je vais l'ajouter tout de suite.

**Comment by oumaymatb** [comment]
Bonjour Monsieur,

Vous trouverez le code dans la branche nommée master. 
Pourriez-vous checker svp ?

Merci,
Oumayma

**Comment by benitoelgringo** [comment]
Super !
Je vois le code désormais.

Merci bien :)

**Comment by oumaymatb** [comment]
Merci à vous !
